Using device: cuda
Traceback (most recent call last):
  File "/home/weishu/Desktop/online_adaptive_cbf/nn_model/train_data.py", line 211, in <module>
    train_dataX, train_dataY, test_dataX, test_dataY, scaler = load_and_preprocess_data(
  File "/home/weishu/Desktop/online_adaptive_cbf/nn_model/train_data.py", line 104, in load_and_preprocess_data
    X_scaled = scaler.transform(X_transformed)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/sklearn/utils/_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/sklearn/preprocessing/_data.py", line 1062, in transform
    X = validate_data(
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/sklearn/utils/validation.py", line 2965, in validate_data
    _check_n_features(_estimator, X, reset=reset)
  File "/home/weishu/anaconda3/envs/online_cbf/lib/python3.9/site-packages/sklearn/utils/validation.py", line 2829, in _check_n_features
    raise ValueError(
ValueError: X has 6 features, but StandardScaler is expecting 5 features as input.
